INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (1, 'Café Caramel con Chocolate', '59.9', 'cafe_01', 1);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (2, 'Café Frio con Chocolate Grande', '49.9', 'cafe_02', 1);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (3, 'Latte Frio con Chocolate Grande', '54.9', 'cafe_03', 1);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (4, 'Latte Frio con Chocolate Grande', '54.9', 'cafe_04', 1);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (5, 'Malteada Fria con Chocolate Grande', '54.9', 'cafe_05', 1);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (6, 'Café Mocha Caliente Chico', '39.9', 'cafe_06', 1);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (7, 'Café Mocha Caliente Grande con Chocolate', '59.9', 'cafe_07', 1);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (8, 'Café Caliente Capuchino Grande', '59.9', 'cafe_08', 1);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (9, 'Café Mocha Caliente Mediano', '49.9', 'cafe_09', 1);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (10, 'Café Mocha Frio con Caramelo Mediano', '49.9', 'cafe_10', 1);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (11, 'Café Mocha Frio con Chocolate Mediano', '49.9', 'cafe_11', 1);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (12, 'Café Espresso', '29.9', 'cafe_12', 1);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (13, 'Café Capuchino Grande con Caramelo', '59.9', 'cafe_13', 1);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (14, 'Café Caramelo Grande', '59.9', 'cafe_14', 1);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (15, 'Paquete de 3 donas de Chocolate', '39.9', 'donas_01', 4);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (16, 'Paquete de 3 donas Glaseadas', '39.9', 'donas_02', 4);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (17, 'Dona de Fresa ', '19.9', 'donas_03', 4);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (18, 'Dona con Galleta de Chocolate ', '19.9', 'donas_04', 4);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (19, 'Dona glass con Chispas Sabor Fresa ', '19.9', 'donas_05', 4);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (20, 'Dona glass con Chocolate ', '19.9', 'donas_06', 4);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (21, 'Dona de Chocolate con MÁS Chocolate ', '19.9', 'donas_07', 4);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (22, 'Paquete de 3 donas de Chocolate ', '39.9', 'donas_08', 4);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (23, 'Paquete de 3 donas con Vainilla y Chocolate ', '39.9', 'donas_09', 4);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (24, 'Paquete de 6 Donas', '69.9', 'donas_10', 4);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (25, 'Paquete de 3 Variadas', '39.9', 'donas_11', 4);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (26, 'Dona Natural con Chocolate', '19.9', 'donas_12', 4);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (27, 'Paquete de 3 Donas de Chocolate con Chispas', '39.9', 'donas_13', 4);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (28, 'Dona Chocolate y Coco', '19.9', 'donas_14', 4);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (29, 'Paquete Galletas de Chocolate', '29.9', 'galletas_01', 6);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (30, 'Paquete Galletas de Chocolate y Avena', '39.9', 'galletas_02', 6);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (31, 'Paquete de Muffins de Vainilla', '39.9', 'galletas_03', 6);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (32, 'Paquete de 4 Galletas de Avena', '24.9', 'galletas_04', 6);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (33, 'Galletas de Mantequilla Variadas', '39.9', 'galletas_05', 6);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (34, 'Galletas de sabores frutales', '39.9', 'galletas_06', 6);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (35, 'Hamburguesa Sencilla', '59.9', 'hamburguesas_01', 2);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (36, 'Hamburguesa de Pollo', '59.9', 'hamburguesas_02', 2);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (37, 'Hamburguesa de Pollo y Chili', '59.9', 'hamburguesas_03', 2);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (38, 'Hamburguesa Queso y  Pepinos', '59.9', 'hamburguesas_04', 2);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (39, 'Hamburguesa Cuarto de Libra', '59.9', 'hamburguesas_05', 2);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (40, 'Hamburguesa Doble Queso', '69.9', 'hamburguesas_06', 2);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (41, 'Hot Dog Especial', '49.9', 'hamburguesas_07', 2);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (42, 'Paquete 2 Hot Dogs', '69.9', 'hamburguesas_08', 2);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (43, '4 Rebanadas de Pay de Queso', '69.9', 'pastel_01', 5);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (44, 'Waffle Especial', '49.9', 'pastel_02', 5);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (45, 'Croissants De la casa', '39.9', 'pastel_03', 5);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (46, 'Pay de Queso', '19.9', 'pastel_04', 5);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (47, 'Pastel de Chocolate', '29.9', 'pastel_05', 5);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (48, 'Rebanada Pastel de Chocolate', '29.9', 'pastel_06', 5);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (49, 'Pizza Spicy con Doble Queso', '69.9', 'pizzas_01', 3);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (50, 'Pizza Jamón y Queso', '69.9', 'pizzas_02', 3);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (51, 'Pizza Doble Queso', '69.9', 'pizzas_03', 3);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (52, 'Pizza Especial de la Casa', '69.9', 'pizzas_04', 3);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (53, 'Pizza Chorizo', '69.9', 'pizzas_05', 3);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (54, 'Pizza Hawaiana', '69.9', 'pizzas_06', 3);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (55, 'Pizza Tocino', '69.9', 'pizzas_07', 3);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (56, 'Pizza Vegetales y Queso', '69.9', 'pizzas_08', 3);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (57, 'Pizza Pepperoni y Queso', '69.9', 'pizzas_09', 3);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (58, 'Pizza Aceitunas y Queso', '69.9', 'pizzas_10', 3);
INSERT INTO "Producto"("id", "nombre", "precio", "imagen", "categoriaId") VALUES (59, 'Pizza Queso, Jamón y Champiñones', '69.9', 'pizzas_11', 3);
